function moreClick(){
    $("#postPile").find(".year").last().find(".postContainer").append(`<div class="post"> <div class="postTop pink"> <div class="postDay"> <div class="day"></div> <span>12/09</span> </div> <h1>Title</h1> </div> <div class="postBody"> <div class="postContent"> Caros amigos. </div> </div> <div class="postEditorOptions"> <ul> <li> <img src="img/erase.png"/> <span> Apagar</span> </li> <li> <img src="img/mark.png"/> <span> Marcar</span> </li> </ul> </div> </div>`)
    $("#postPile").find(".year").last().find(".postContainer").append(`<div class="post"> <div class="postTop pink"> <div class="postDay"> <div class="day"></div> <span>12/09</span> </div> <h1>Title</h1> </div> <div class="postBody"> <div class="postContent"> Caros amigos. </div> </div> <div class="postEditorOptions"> <ul> <li> <img src="img/erase.png"/> <span> Apagar</span> </li> <li> <img src="img/mark.png"/> <span> Marcar</span> </li> </ul> </div> </div>`)
    $("#postPile").find(".year").last().find(".postContainer").append(`<div class="post"> <div class="postTop pink"> <div class="postDay"> <div class="day"></div> <span>12/09</span> </div> <h1>Title</h1> </div> <div class="postBody"> <div class="postContent"> Caros amigos. </div> </div> <div class="postEditorOptions"> <ul> <li> <img src="img/erase.png"/> <span> Apagar</span> </li> <li> <img src="img/mark.png"/> <span> Marcar</span> </li> </ul> </div> </div>`)


    $("#postPile").append(`<div class="year"> <div class="yearTime"> 2012 </div> <div class="postContainer"> <div class="post"> <div class="postTop green"> <div class="postDay"> <div class="day"></div> <span>12/09</span> </div> <h1>Title</h1> </div> <div class="postBody"> <div class="postContent"> Desta maneira, a mobilidade dos capitais internacionais possibilita uma melhor visão global dos índices pretendidos. Todas estas questões, devidamente ponderadas, levantam dúvidas sobre se a adoção de políticas descentralizadoras representa uma abertura para a melhoria das diretrizes de desenvolvimento para o futuro. Assim mesmo, a contínua expansão de nossa atividade exige a precisão e a definição da gestão inovadora da qual fazemos parte. O incentivo ao avanço tecnológico, assim como a hegemonia do ambiente político estende o alcance e a importância do retorno esperado a longo prazo. </div> </div> <div class="postEditorOptions"> <ul> <li> <img src="img/erase.png"/> <span> Apagar</span> </li> <li> <img src="img/mark.png"/> <span> Marcar</span> </li> </ul> </div> </div> <div class="post"> <div class="postTop pink"> <div class="postDay"> <div class="day"></div> <span>12/09</span> </div> <h1>Title</h1> </div> <div class="postBody"> <div class="postContent">postteste1 </div> </div> <div class="postEditorOptions"> <ul> <li> <img src="img/erase.png"/> <span> Apagar</span> </li> <li> <img src="img/mark.png"/> <span> Marcar</span> </li> </ul> </div> </div> <div class="post"> <div class="postTop purple"> <div class="postDay"> <div class="day"></div> <span>12/09</span> </div> <h1>Title</h1> </div> <div class="postBody"> <div class="postContent">posteteste2

 </div> </div> <div class="postEditorOptions"> <ul> <li> <img src="img/erase.png"/> <span> Apagar</span> </li> <li> <img src="img/mark.png"/> <span> Marcar</span> </li> </ul> </div> </div> <div class="post"> <div class="postTop blue"> <div class="postDay"> <div class="day"></div> <span>12/09</span> </div> <h1>Title</h1> </div> <div class="postBody"> <div class="postContent"> postteste </div> </div> <div class="postEditorOptions"> <ul> <li> <img src="img/erase.png"/> <span> Apagar</span> </li> <li> <img src="img/mark.png"/> <span> Marcar</span> </li> </ul> </div> </div> </div> </div>`);
    uploadDestiny();
}